### ISSUE TITLE
Create a working styleguide site

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/styleguide#1]
Much like http://nerds.airbnb.com, we'd like to have a site to showcase the LP dev team.

Currently we have engineering.lonelyplanet.com and rizzo.lonelyplanet.com, but they're sad and lonely and need a facelift. Plus, they don't reflect what LP is currently doing.

### TODO's
- [ ] Pick a method for rendering
    * Static site? Jekyll? Gatbsy?

#### Blog
- [ ] Add blog
Should we...
* Have links to blog posts on Medium?
...or...
* Have a blog built in here

#### Pages
* [ ] Have a page for coding standards
* [ ] Have a page for team
* [ ] Have a page for community contributions
* [ ] Have a page for current styleguide aka backpack and sketch

**Comment by thomasthesecond** [comment]
http://airbnb.io/
